### ISSUE TITLE
Support toy-like API

### ISSUE THREAD

**Issue by ryanmiville** [drewolson/clip#2]
Are you familiar with [toy](https://github.com/Hackder/toy)? The community seems to like it for decoders and I think it would be valuable to have a similar API here as well.

It could look something like this:

```gleam
pub type Person {
  Person(name: String, age: Int, married: Bool, kids: List(String))
}

pub fn command() -> Command(Person) {
  use name <- clip.opt(opt.new("name") |> opt.short("n") |> opt.help("Your name"))
  use married <- clip.flag(flag.new("married"))
  use age <- clip.opt(opt.new("age") |> opt.int |> opt.help("Your age"))
  use kids <- clip.arg_many(arg.new("kids") |> arg.help("Your kids' names"))
  clip.pure(Person(name:, age:, married:, kids:))
}

pub fn main() {
  let result =
    command()
    |> clip.run(["-n", "Drew", "--married", "--age", "42", "Bobby", "Joy"])
  case result {
    Ok(person) -> person |> string.inspect |> io.println
    Error(e) -> io.println_error(e)
  }
}
```

I have been working on a similar library ([clad](https://github.com/ryanmiville/clad)), but I think you have a better foundation here. It seems an API like this is pretty easy to achieve. I was able to quickly get the above example working with these changes:

```gleam
pub fn apply(ma: Command(a), mf: fn(a) -> Command(b)) -> Command(b) {
  let f = fn(args) {
    use #(ra, args1) <- result.try(ma.f(args))
    mf(ra).f(args1)
  }
  Command(info: ma.info, f:)
}

pub fn opt(opt: Opt(a), next: fn(a) -> Command(b)) -> Command(b) {
  apply(Command(info: opt.to_arg_info(opt), f: opt.run(opt, _)), next)
}

pub fn flag(flag: Flag, next: fn(Bool) -> Command(a)) -> Command(a) {
  apply(Command(info: flag.to_arg_info(flag), f: flag.run(flag, _)), next)
}

pub fn arg(arg: Arg(a), next: fn(a) -> Command(b)) -> Command(b) {
  apply(Command(info: arg.to_arg_info(arg), f: arg.run(arg, _)), next)
}

pub fn arg_many(arg: Arg(a), next: fn(List(a)) -> Command(b)) -> Command(b) {
  apply(Command(info: arg.to_arg_info_many(arg), f: arg.run_many(arg, _)), next)
}

pub fn arg_many1(arg: Arg(a), next: fn(List(a)) -> Command(b)) -> Command(b) {
  apply(Command(info: arg.to_arg_info_many1(arg), f: arg.run_many1(arg, _)), next)
}
```

I'm sure there is more work to fully support it, but conceptually what do you think?

**Comment by drewolson** [comment]
Thanks for the comment! When I initially started working on `clip`, this monadic style API was exactly where I started. However, there were two problems with this design.

First, by definition, a monadic API is more powerful than an applicative API. But with this power comes challenges. Let's look at the types:

```gleam
pub fn apply(mf: Command(fn(a) -> b), ma: Command(a)) -> Command(b)
```

This is the current applicative-style API for `clip`. Notice that you have direct access to two Commands. This means you can merge their `arg_info` when you run `apply` to produce all the necessary data for adding `help` text.

```gleam
pub fn bind(ma: Command(a), f: fn(a) -> Command(b)) -> Command(b)
```

In a monadic-style API, you can see from the types that `Command(b)` _depends on the output_ of `Command(a)`. This means you don't have access to `Command(b)` until you successfully run `Command(a)` and use its output to product `Comand(b)`. This means I'm unable to produce help text for these two commands and merge them without actually running the commands.

You can see this problem concretely with your proposed implementation of `apply`:

```gleam
pub fn apply(ma: Command(a), mf: fn(a) -> Command(b)) -> Command(b) {
  let f = fn(args) {
    use #(ra, args1) <- result.try(ma.f(args))
    mf(ra).f(args1)
  }
  Command(info: ma.info, f:)
}
```

Notice that this ignores the `info` for `Command(b)`. Why? Because you don't have access to it with this design. This means your command cannot have all the necessary information to generate help text.

Second, I don't think we even want to provide the power of a monadic API. I don't want parsing of my second argument to be able to depend on the result of parsing my first argument. This is inherently too powerful in a way that allows bad design for CLI parsing.

I wish there was a way to provide something that looked like a `use`-style API without these drawbacks, but I wasn't able to find one. Other languages have syntactic sugar for applicative APIs -- OCaml allows using, by convention, the `let+` and `and+` operators to provide a nicer API for the applicative style (see: https://ocaml.org/manual/5.2/bindingops.html#ss:letop-examples). However, I don't believe I can achieve this in gleam without going the full monadic route.

Thoughts welcome.

**Comment by drewolson** [comment]
As a follow up, here's the generated help text from the `custom-opt-types` example in your fork:

```
$ gleam run -- --help
   Compiled in 0.00s
    Running cli.main
custom-opt-types -- Options with custom types

Usage:

  custom-opt-types [OPTIONS]

Options:

  (--first FIRST)       First
  [--help,-h]           Print this help
```

vs the main repo:

```
$ gleam run -- --help
   Compiled in 0.01s
    Running cli.main
custom-opt-types -- Options with custom types

Usage:

  custom-opt-types [OPTIONS]

Options:

  (--first FIRST)       First
  (--second SECOND)     Second
  (--third THIRD)       Third
  (--fourth FOURTH)     Fourth
  [--help,-h]           Print this help
```

**Comment by ryanmiville** [comment]
Hey thanks for the thorough response! I did get the applicative parsing working with the same strategy as toy, having default values, but I totally forgot about the help message. It's probably possible but makes things much more complicated. 

I'll continue to tinker with this idea, and I'll reach out if I find a good solution that works, but feel free to close this issue.

**Comment by drewolson** [comment]
Thanks for the follow up and definitely let me know if you find a design you like. I went through exactly the same thing you described -- building a `use`-style API until I reached the help text generation and was stumped.
